name = "catatan-diskusi-idadiyah"
compatibility_date = "2025-06-16"
pages_build_output_dir = "."
build = { command = "npm install", upload = { format = "modules" } }

[vars]
# NEON_DATABASE_URL dan MISTRAL_API_KEY akan diset di Cloudflare Pages environment
